### ISSUE TITLE
Murs dans le mode apprentissage

### ISSUE THREAD

**Issue by 4rnaudB** [CHUMneuroepilepsie/VR_Polytechnique#106]
### Checklist

- [x] J'ai donné un titre significatif
- [x] J'ai décrit l'environnement
- [x] J'ai décrit le bug
- [x] J'ai donné la bonne étiquette

### Détails de l'environnement
main

### Description du bug
Les murs `Teleporter` dans le mode apprentissage sont visible et bloque le passage. Aussi je ne vois pas les panneaux d'indications.

**Comment by 4rnaudB** [comment]
@YassineDiouri1 @FatimaGharsallah @EmmanuelDW

**Comment by YassineDiouri1** [comment]
Faut delete le prefab teleporter on en a plus besoin tout est dans checkpointwalls.
Les panneaux sont dans des prefabs je sais pas s’ils ont été mis dans les scenes

**Comment by 4rnaudB** [comment]
Ok est-ce qu'on a une branche avec ces changements vu qu'ils avaient été fait pour le démo?

**Comment by YassineDiouri1** [comment]
J’avais add et delete manuellement pour la demo. Faut le faire dans le main

**Comment by 4rnaudB** [comment]
Ok, si tu peux faire une pr rapide ça serait bien
