### ISSUE TITLE
wow interface

### ISSUE THREAD

**Issue by FatimaGharsallah** [CHUMneuroepilepsie/VR_Polytechnique#120]
### Checklist

- [ ] J'ai donné un titre significatif
- [ ] J'ai décrit la nouvelle caractéristique
- [ ] (optionel) J'ai ajouté des idées sur comment l'implémenter
- [ ] J'ai donné à cette demande la bonne étiquette

### Description de la caractéristique:
Faire des belles interfaces!

**Comment by YassineDiouri1** [comment]
il y a  une erreur dans la police de ce panneaux dans le tutoriel 
![image](https://user-images.githubusercontent.com/113944605/229644500-79b51913-1e34-4eb3-b0ee-36c640b97500.png)
