### ISSUE TITLE
Désactiver le bouton ''supprimer'' l'orsqu'il n'y a pas de profil existant

### ISSUE THREAD

**Issue by FatimaGharsallah** [CHUMneuroepilepsie/VR_Polytechnique#69]
### Checklist

- [x] J'ai donné un titre significatif
- [x] J'ai décrit la nouvelle caractéristique
- [ ] (optionel) J'ai ajouté des idées sur comment l'implémenter
- [x] J'ai donné à cette demande la bonne étiquette

### Description de la caractéristique:
Dans le sous-menu Profils, désactiver le bouton permettant de supprimer un profil l'orsqu'il n'y a pas de profil existant.

**Comment by 4rnaudB** [comment]
Fait avec #70
