### ISSUE TITLE
Message d'avertissement avant de retourner au menu principal (menu de fin)

### ISSUE THREAD

**Issue by FatimaGharsallah** [CHUMneuroepilepsie/VR_Polytechnique#71]
### Checklist

- [ ] J'ai donné un titre significatif
- [ ] J'ai décrit la nouvelle caractéristique
- [ ] (optionel) J'ai ajouté des idées sur comment l'implémenter
- [ ] J'ai donné à cette demande la bonne étiquette

### Description de la caractéristique:
Dans le menu de fin, il n'y a pas de message d'avertissement qui indique que les résultats n'ont pas été sauvegardés si on clique pour retourner vers le menu principal (et que les résultats n'ont pas été sauvegardés).

**Comment by 4rnaudB** [comment]
C'est pas ce que tu as implémenté ici? #54

**Comment by 4rnaudB** [comment]
Fait avec #72
