### ISSUE TITLE
Rendering des fleurs

### ISSUE THREAD

**Issue by 4rnaudB** [CHUMneuroepilepsie/VR_Polytechnique#84]
### Checklist

- [x] J'ai donné un titre significatif
- [x] J'ai décrit la nouvelle caractéristique
- [ ] (optionel) J'ai ajouté des idées sur comment l'implémenter
- [x] J'ai donné à cette demande la bonne étiquette

### Description de l'amélioration
Les fleurs bougent beaucoup trop et je pense que ça diminue significativement les fps. On peut pas diminuer le vent ou limiter leur mouvement?

**Comment by EmmanuelDW** [comment]
J'ai essayé plein de manière de faire mais chaque fois que je touche au settings toutes les fleurs et le grass disparaissent. Il faudrait voir si ça fait ça aussi pour vous.

![image](https://user-images.githubusercontent.com/55562569/221726014-3bbe9436-52f1-4676-adfe-bca16b0a27e0.png)

L'option est dans terrain toolbox en bas. Il faut faire apply à tout les terrains.

**Comment by FatimaGharsallah** [comment]
@EmmanuelDW il faut le faire sur chaque prefab rajouté ici 
![image](https://user-images.githubusercontent.com/80424041/222296349-fc21d35e-e17b-47d4-b42e-c13aa3b58f43.png)
J'ai testé en diminuant de 5 à 2, mais ça ne change pas grand chose... Est-ce qu'on veut enlever le vent complètement ou non ?

**Comment by EmmanuelDW** [comment]
Je pense bien que oui on peut juste le désactiver sur tout les terrains ou le set à 0.
