### ISSUE TITLE
Menu pause presque pas visible

### ISSUE THREAD

**Issue by lulubou** [CHUMneuroepilepsie/VR_Polytechnique#87]
### Checklist

- [X] J'ai donné un titre significatif
- [ ] J'ai décrit l'environnement
- [X] J'ai décrit le bug
- [X] J'ai décris les étapes pour reproduire le bug
- [X] J'ai inclus des captures d'écrans
- [X] J'ai donné la bonne étiquette

### Détails de l'environnement

Version de Unity:

Version de C#: 

### Description du bug
Les options du menu pause sont en noir et pratiquement pas visibles lorsque le curseur n'est pas au-dessus de celles-ci (voir image).

Message d'erreur du terminal:
Aucun

### Étapes pour reproduire le bug
Ouvrir en mode évaluation et peser sur pause pour voir le menu pause.

### Captures d'écran:
![image](https://user-images.githubusercontent.com/80421345/222194986-a1dc1bb3-e314-481a-9c4b-89cde21a121f.png)

**Comment by 4rnaudB** [comment]
Déjà réglé dans #80

**Comment by lulubou** [comment]
Parfait
