### ISSUE TITLE
Bouton du prefab player sur toute les scenes

### ISSUE THREAD

**Issue by YassineDiouri1** [CHUMneuroepilepsie/VR_Polytechnique#91]
### Checklist

- [x] J'ai donné un titre significatif
- [x] J'ai décrit la nouvelle caractéristique
- [x] (optionel) J'ai ajouté des idées sur comment l'implémenter
- [x] J'ai donné à cette demande la bonne étiquette

### Description de la caractéristique:
Sur certaines branches les boutons et évent associé dans le prefab `player `=> playerInput, =>Events => PauseMenu sont actifs et dans d'autre non. 
Une fois que tout les boutons sont associé il faut les apply au prefab pour que ce soit mis dans toutes les branches

### Suggestion pour l'implémentation:
Une fois que tout les boutons sont associé il faut les apply au prefab pour que ce soit mis dans toutes les branches
Aussi, modifier pour allowPlayerMovement dans CustomInputAction le grip par triggerPressed(Left hand HTC Vive Controller)

**Comment by 4rnaudB** [comment]
Pour le tutoriel j'ai gardé les fonctions propres au tutoriel dans Tutoriel seulement. Pour le triggerPressed je te laisse voir avec ta focntion mais je vais finaliser le trigger lorsque je vais pouvoir placer les objets.

**Comment by YassineDiouri1** [comment]
j'ai mis l'issue car je me suis rendu compte que c'etait pas uniforme dans toutes les scènes, donc pour qu'on oublie pas de check a la fin que les boutons nécéssaire a chaque scène soit bien actif
