### ISSUE TITLE
endzone non fonctionnel dans Mode apprentissage

### ISSUE THREAD

**Issue by YassineDiouri1** [CHUMneuroepilepsie/VR_Polytechnique#93]
### Checklist

- [x] J'ai donné un titre significatif
- [] J'ai décrit la nouvelle caractéristique
- [] (optionel) J'ai ajouté des idées sur comment l'implémenter
- [x] J'ai donné à cette demande la bonne étiquette

### Description de la caractéristique:
Dans le mode apprentissage la endZone ne fonctionne pas : on peut entrer dedans et le message  apparait mais on peut pas cliquer sur aucun des deux boutons.

**Comment by 4rnaudB** [comment]
Je n'ai pas ce bug, dans quelle branche as-tu eu ce problème?

**Comment by YassineDiouri1** [comment]
j'etais dans le main de souvenir

**Comment by 4rnaudB** [comment]
Okok pcq je viens de tester dans le main et ça fonctionne

**Comment by YassineDiouri1** [comment]
Tu as raison ca fonctionne bien
